export const CREATE_FARM = "CREATE_FARM";
export const UPDATE_FARM = "CREATE_FARM";
export const DELETE_FARM = "CREATE_FARM";
export const CREATE_FARM_ERROR = "CREATE_FARM_ERROR";
export const UPDATE_FARM_ERROR = "UPDATE_FARM_ERROR";
export const DELETE_FARM_ERROR = "DELETE_FARM_ERROR";