export const CREATE_USER_ORDER = "CREATE_USER_ORDER";
export const CREATE_USER_ORDER_ERROR = "CREATE_USER_ORDER_ERROR";

export const CREATE_FARM_ORDER = "CREATE_FARM_ORDER";
export const CREATE_FARM_ORDER_ERROR = "CREATE_FARM_ORDER_ERROR";