export const CREATE_PRODUCT = "CREATE_PRODUCT"; 
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"; 
export const DELETE_PRODUCT = "DELETE_PRODUCT"; 

export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";